[package]
name = "sixth_lesson"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]



[[bin]]
name ="pointer"
path ="src/pointer.rs"

[[bin]]
name ="smart"
path ="src/smart_pointers.rs"